//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CM_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int CustNo { get; set; }
        public string RecordId { get; set; }
        public System.DateTime DateOrdered { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Record Record { get; set; }
    }
}
